language: python

sudo: false

python:
  - 3.5
  - 3.6.0

install:
  - ./install-dev.sh

script:
  - flake8
  - python setup.py test --coverage -q --sequential
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6.0 ]]; then python setup.py test --coveralls; fi
  - python setup.py test --io uv --sequential

notifications:
  email: false
