language: python

sudo: false

python:
  - 3.5.1

install:
  - pip install -r requirements-dev.txt
  - pip install git+https://github.com/quantmind/pulsar.git

script:
  - flake8
  - python setup.py test --coverage -q
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.1 ]]; then python setup.py test --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
