language: python

sudo: false

python:
  - 3.4.3
  - 3.5.1

install:
  - pip install -r requirements-dev.txt
  - python setup.py install

script:
  - flake8
  - rm -rf cloud
  - python -m runtests --coverage
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.1 ]]; then python -m runtests --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
